
name: ANN Tests Automated Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        environment-file: environment.yml
        activate-environment: ann-tests
        auto-activate-base: false
    - name: Run code checks
      run: |
        conda activate ann-tests
        flake8 .
        black --check .
        isort --check .