
name: ANN Tests Automated Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update -f environment.yml --name base
    - name: Check for code lint with flake8
      run: |
        flake8 .
    - name: Check code formatting with black
      run: |
        black --check .
    - name: Check dependency sorting with isort
      run: |
        isort --check .